server:
  port: 10001
spring:  
  application:
    name: SysConfiguration
  profiles:
    active: native
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:10000/}
        password: admin
        username: admin
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
