server:
  port: 10003
  servlet:
    context-path: /auth

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:10000/}
        password: admin
        username: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ctos?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10002/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"